basePath = "go.mlcdf.fr"

[index]
description = "aa"
extra_head = ""
title = "Maxime's go packages"

[repos]

[repos."/go/envpath"]
description = ""
name = "envpath"
repo = "https://github.com/mlcdf/go/envpath/"
